apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn
  namespace: keptn
spec:
  chart:
    spec:
      chart: keptn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keptn
      version: 0.16.0
  interval: 5m0s
