apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn-flux-integration
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keptn-flux-integration
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keptn-flux-integration
      version: 0.16.3
  interval: 5m0s
  values:
    keptn:
      url: https://keptn.ortelius.io/api/v1/event
    apps:
    - name: podtato-head
      namespace: podtato-kustomize
      kind: Kustomization
      labels:
        keptnProject: flux-demo
        keptnService: podtato-head
        keptnStage: dev
        keptnType: sh.keptn.event.test.delivery.triggered  
      matchLabels:
            app.kubernetes.io/name: podtato-head
        integrationUrl: http://keptn-flux-integration.flux-system.svc.cluster.local:80