apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keptn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keptn-flux-integration
      version: 0.14.0
  interval: 1m0s
