apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: alert
  namespace: flux-system
spec:
  summary: default
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"